### ISSUE TITLE
Sailthru classes

### ISSUE THREAD

**Issue by bobbrodie** [sailthru/sailthru-magento-extension#29]
The sailthru_api classes are not technically helpers, they're classes that work together and have a specific purpose. Since Magento is built on Zend Framework, it would be much preferred to have these converted to proper Zend Framework classes and moved to the lib/ folder. Something like lib/Sailthru/Email.

**Comment by silverman63** [comment]
Sailthru Client Library has been moved to a lib folder in latest.
