### ISSUE TITLE
Sailthru_Client_Exception

### ISSUE THREAD

**Issue by bobbrodie** [sailthru/sailthru-magento-extension#31]
Do we really need to use Sailthru_Client_Exception? It extends Exception but adds no value whatsoever.

If you keep the Sailthru classes in Magento (not recommended), you should be extending Mage_Exception.

If you move the Sailthru classes to Zend Framework classes, you should be extending Zend_Exception.

If you're not adding any value, just throw a Mage_Exception or Zend_Exception rather than have a blank class.

**Comment by silverman63** [comment]
Hi @bobbrodie, in the latest version of the plugin, our client library now throws Sailthru_Client_Exception whenever it gets an error response from the API. The Sailthru_Client_Exception is now used to help bubble up and centralize Sailthru-related issues.
