### ISSUE TITLE
Method does not exists

### ISSUE THREAD

**Issue by josh--** [sailthru/sailthru-magento-extension#34]
The observer definitions located @ app/code/local/Sailthru/Email/etc/config.xml set up a call to a method that does not exist in the observer model.            

 <checkout_quote_destroy>
                <observers>
                    <sailthru_checkout_quote_destroy>
                        <type>Singleton</type>
                        <class>Sailthru_Email_Model_Observer</class>
                        <method>pushPurchaseOrderSuccessToSailthru2</method>
                    </sailthru_checkout_quote_destroy>
                </observers>
            </checkout_quote_destroy>

The side effect prevents a user from reaching the order success page. Is the 2 a typo or is the function just missing all together?

**Comment by silverman63** [comment]
This is no longer an aspect of the plugin.
