### ISSUE TITLE
Horizon settings should include an option for Async/Sync 

### ISSUE THREAD

**Issue by nickgundry** [sailthru/sailthru-magento-extension#36]
On the Sailthru docs site there are options for adding Horizon JS via Asynchronous and Synchronous loading. 

We should add an option to the Horizon screen for the user to decide which type of loading they want to use. 

http://docs.sailthru.com/node/59

**Comment by silverman63** [comment]
While Horizon is still an option, it has been deprecated in favor of the Sailthru Script Tag.
