### ISSUE TITLE
Large log files

### ISSUE THREAD

**Issue by Zefiryn** [sailthru/sailthru-magento-extension#39]
I have noticed that in several places this module is logging entire objects (ie. https://github.com/sailthru/sailthru-magento-extension/blob/master/app/code/local/Sailthru/Email/Model/Observer.php#L75) which is really big portion of data and in quick time it may cause serious issues to the server disk space. Magento model classes has debug() method that shows only data part of the model without unnecessary child classes elements. If those log lines need to be there I would suggest logging $customer->debug() instead of $customer

**Comment by silverman63** [comment]
I can't quite track down the commit, but this seems to have been resolved by June 2014. I actually didn't know about the debug method. Will be very helpful in the future!
