### ISSUE TITLE
apiPost method appends curly brackets to file causing curl to not be able to read file

### ISSUE THREAD

**Issue by toddb02** [sailthru/sailthru-magento-extension#41]
public function apiPost($action, $data, array $binary_data_param = array()) {
        $binary_data = array();
        if (!empty ($binary_data_param)) {
            foreach ($binary_data_param as $param) {
                if (isset($data[$param]) && file_exists($data[$param])) {
                    **$binary_data[$param] = '@{' . $data[$param] . '}';**
                    unset($data[$param]);
                    $this->_fileUpload = true;
                }
            }
        }
        $payload = $this->prepareJsonPayload($data, $binary_data);
        return $this->_httpRequest($this->_apiUri . '/' . $action, $payload, 'POST');
    }

The bolded line in the method (found in Sailthru_Email_Model_Client) surrounds the file name causing curl to not be able to open the file. 

Error : Bad response received from http://api.sailthru.com/job. cURL Error: couldn't open file 

If I remove the curly brackets (change line to **$binary_data[$param] = '@' . $data[$param];**) everything works.

**Comment by silverman63** [comment]
The latest version of the plugin uses the latest Sailthru PHP5 client library. I believe this issue should be resolved now, but if not please report it as an issue in the Sailthru PHP5 Client Library repo.
