### ISSUE TITLE
Possibly incorrect controller class name `Sailthru_Horizon_IndexController`

### ISSUE THREAD

**Issue by rpnzl** [sailthru/sailthru-magento-extension#44]
I'm reference the class definition [here](https://github.com/sailthru/sailthru-magento-extension/blob/master/app/code/local/Sailthru/Email/controllers/IndexController.php#L8). We started seeing a `Controller file was loaded but class does not exist` exception referencing the Sailthru module, and this controller file looks to be the only one that doesn't follow the convention of `Sailthru_Email...`.

If you confirm this as a bug I can submit a PR, but I want to be sure I'm not misinterpreting anything.

**Comment by rpnzl** [comment]
Closing, since no response for a long while.

**Comment by silverman63** [comment]
Hi @rpnzl, I can take a look at this at some point. Do you have a way to replicate the error? Agree that it seems odd to not follow the structure.

**Comment by silverman63** [comment]
This file has been removed from the latest version of the plugin.
