### ISSUE TITLE
Sailthru_Email_Model_Client_Purchase::_getTenders() raises PHP notice

### ISSUE THREAD

**Issue by jeffreyhill** [sailthru/sailthru-magento-extension#45]
```
ERR (3): Notice: Undefined index: title in /app/code/local/Sailthru/Email/Model/Client/Purchase.php on line 214
```

Line in question: 

```
if ($tenders['title'] == null) {
                return '';
            }
```

$tenders is nested in another array, as is typical with these API calls.

**Comment by silverman63** [comment]
I don't believe this should be an issue anymore with latest plugin. Closing. Let me know if you experience any more issues with this.
